//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InactivityBot.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InactivityBot.Ressources.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Wars 2 account name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please also specifiy the last 4 digits of your GW2 account name..
        /// </summary>
        internal static string AccountName_DiggitsMissing {
            get {
                return ResourceManager.GetString("AccountName_DiggitsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        internal static string Embed_AccountName {
            get {
                return ResourceManager.GetString("Embed_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you find the community?.
        /// </summary>
        internal static string Embed_Found {
            get {
                return ResourceManager.GetString("Embed_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do you want to be a part of this community?.
        /// </summary>
        internal static string Embed_Reason {
            get {
                return ResourceManager.GetString("Embed_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application!.
        /// </summary>
        internal static string Embed_Title {
            get {
                return ResourceManager.GetString("Embed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Emotes are not allowed!.
        /// </summary>
        internal static string Emote_CustomEmote {
            get {
                return ResourceManager.GetString("Emote_CustomEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current Application Emote is: {0}.
        /// </summary>
        internal static string Emote_GetEmote {
            get {
                return ResourceManager.GetString("Emote_GetEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Emoji was specified!.
        /// </summary>
        internal static string Emote_MissingEmote {
            get {
                return ResourceManager.GetString("Emote_MissingEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set the Application emoji..
        /// </summary>
        internal static string Emote_Success {
            get {
                return ResourceManager.GetString("Emote_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you find the community?.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the destination channel..
        /// </summary>
        internal static string GetChannel_NotFound {
            get {
                return ResourceManager.GetString("GetChannel_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current destination channel is: {0}.
        /// </summary>
        internal static string GetChannel_Success {
            get {
                return ResourceManager.GetString("GetChannel_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do you want to be a part of this community?.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a channel by referencing it with # and the channel name. e.g. #inactivity.
        /// </summary>
        internal static string SetChannel_NoChannel {
            get {
                return ResourceManager.GetString("SetChannel_NoChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully set the destination channel!.
        /// </summary>
        internal static string SetChannel_Success {
            get {
                return ResourceManager.GetString("SetChannel_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No destination channel was set, prior to calling this command. Please set one using the command &quot;application channel [channel]&quot;.
        /// </summary>
        internal static string Start_MissingChannel {
            get {
                return ResourceManager.GetString("Start_MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply for this community, please react with {0}.
        /// </summary>
        internal static string Start_Reaction {
            get {
                return ResourceManager.GetString("Start_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your application!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot will no longer respond to new messages. Please react to the message again to complete the Application!.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
    }
}
